### ISSUE TITLE
Fully valid puissant not getting evalutated 

### ISSUE THREAD

**Issue by Code0x2** [BNB48Club/puissant_service#1]
Fully valid puissants are being ignored and dropped after expiry
I have puissant [0x083fb5b5bd504612944d958f1ff97502](https://explorer.bnb48.club/api/v1/puissant/0x083fb5b5bd504612944d958f1ff97502) which was sent 2022-11-12T10:18:56+08:00, and block [22979580](https://bscscan.com/block/22979580) broadcasted at Nov-12-2022 02:19:01 AM +UTC. A public transaction within my puissant was included in that block, however the remaining puissant txs were not, even though it was fully possible to. The puissant was sent at XX:18:56, but block produced at XX:19:01, providing 5 seconds to evaluate it on the block. Its later dropped after the expiry has been reached on the puissant

**Comment by Jolly23** [comment]
Thanks for the detail. I will check this out today.

**Comment by Jolly23** [comment]
Hello @Code0x2 ,

It turns out that the [22979580](https://bscscan.com/block/22979580) is a very busy block. 
The status of puissant you sent was actually *beaten*

There is a reporting issue on the result-query and we appreciate you bringing this up, we will fix.
